export const legacy: Record<string, string> = {
  recipes: 'guides/recipes/',
  api: 'reference/',
  'list-company-jobs': 'reference/#listCompanyJobs',
  'fetch-job': 'reference/#fetchJob',
  resolve: 'reference/#resolveCompany',
  homepage: 'guides/homepages/',
  scrapers: 'reference/#scrapers',
  errors: 'reference/#JobNotFoundError',
  guides: 'guides/',
  resolution: 'guides/resolution/',
  search: 'guides/search/',
  registry: 'guides/registry/',
  state: 'guides/state/',
  caching: 'guides/caching/',
  boards: 'guides/boards/',
  browsers: 'guides/browser/',
  contributing: 'guides/adding-a-scraper/',
};
