import { type Company } from './companies.ts';

/**
 * The companies this package already knows how to scrape. On first run this
 * list is copied to `~/.job-scraper/companies.json`, which then takes over as
 * the live registry; companies resolved at runtime get appended there
 * rather than here, so this file only needs updating when a scraper is added.
 */
export const seedCompanies: Company[] = [
  {
    name: 'Abnormal AI',
    scraper: 'GreenhouseScraper',
    slug: 'abnormalsecurity',
    homepage: 'https://abnormal.ai',
  },
  {
    name: 'Affirm',
    scraper: 'GreenhouseScraper',
    slug: 'affirm',
    homepage: 'https://www.affirm.com',
  },
  {
    name: 'Airbnb',
    scraper: 'GreenhouseScraper',
    slug: 'airbnb',
    domains: ['careers.airbnb.com'],
    homepage: 'https://www.airbnb.com',
  },
  {
    name: 'Airtable',
    scraper: 'GreenhouseScraper',
    slug: 'airtable',
    homepage: 'https://airtable.com',
  },
  {
    name: 'Amplitude',
    scraper: 'GreenhouseScraper',
    slug: 'amplitude',
    homepage: 'https://amplitude.com',
  },
  {
    name: 'Anduril',
    scraper: 'GreenhouseScraper',
    slug: 'andurilindustries',
    homepage: 'https://www.anduril.com',
  },
  {
    name: 'Anrok',
    scraper: 'AshbyScraper',
    slug: 'anrok',
    homepage: 'https://anrok.com',
  },
  {
    name: 'Anthropic',
    scraper: 'GreenhouseScraper',
    slug: 'anthropic',
    homepage: 'https://www.anthropic.com',
  },
  {
    name: 'Apollo.io',
    scraper: 'GreenhouseScraper',
    slug: 'apolloio',
    homepage: 'https://www.apollo.io',
  },
  {
    name: 'Applied Compute',
    scraper: 'AshbyScraper',
    slug: 'Applied Compute',
    homepage: 'https://appliedcompute.com',
  },
  {
    name: 'Applied Intuition',
    scraper: 'AshbyScraper',
    slug: 'applied',
    homepage: 'https://www.appliedintuition.com',
  },
  {
    name: 'AppLovin',
    scraper: 'GreenhouseScraper',
    slug: 'applovin',
    homepage: 'https://www.applovin.com',
  },
  {
    name: 'Arcade',
    scraper: 'AshbyScraper',
    slug: 'arcade-ai',
    homepage: 'https://www.arcade.ai',
  },
  {
    name: 'Arcadia',
    scraper: 'RipplingScraper',
    slug: 'arcadiacareers',
    domains: ['arcadia.com'],
    homepage: 'https://www.arcadia.com',
  },
  {
    name: 'Arena',
    scraper: 'AshbyScraper',
    slug: 'arena',
    homepage: 'https://arena.ai',
  },
  {
    name: 'Artie',
    scraper: 'AshbyScraper',
    slug: 'artie',
    homepage: 'https://artie.com',
  },
  {
    name: 'Asana',
    scraper: 'GreenhouseScraper',
    slug: 'asana',
    homepage: 'https://asana.com',
  },
  {
    name: 'Assort Health',
    scraper: 'AshbyScraper',
    slug: 'assorthealth',
    homepage: 'https://www.assorthealth.com',
  },
  {
    name: 'Astera Labs',
    scraper: 'GreenhouseScraper',
    slug: 'asteralabs',
    homepage: 'https://www.asteralabs.com',
  },
  {
    name: 'Autodesk',
    scraper: 'WorkdayScraper',
    slug: 'autodesk.wd1.Ext',
    domains: ['careers.autodesk.com'],
    homepage: 'https://www.autodesk.com',
  },
  {
    name: 'Avoca',
    scraper: 'AshbyScraper',
    slug: 'avoca',
    homepage: 'https://www.avoca.ai',
  },
  {
    name: 'Baseten',
    scraper: 'AshbyScraper',
    slug: 'baseten',
    homepage: 'https://www.baseten.co',
  },
  {
    name: 'Basis',
    scraper: 'AshbyScraper',
    slug: 'basis-ai',
    homepage: 'https://www.getbasis.ai',
  },
  {
    name: 'Block',
    scraper: 'GreenhouseScraper',
    slug: 'block',
    homepage: 'https://block.xyz',
  },
  {
    name: 'Braintrust',
    scraper: 'AshbyScraper',
    slug: 'braintrust',
    homepage: 'https://www.braintrust.dev',
  },
  {
    name: 'Brex',
    scraper: 'GreenhouseScraper',
    slug: 'brex',
    domains: ['careers.brex.com'],
    homepage: 'https://www.brex.com',
  },
  {
    name: 'Browserbase',
    scraper: 'AshbyScraper',
    slug: 'browserbase',
    homepage: 'https://www.browserbase.com',
  },
  {
    name: 'Buildkite',
    scraper: 'GreenhouseScraper',
    slug: 'buildkite',
    homepage: 'https://buildkite.com',
  },
  {
    name: 'Burnt',
    scraper: 'GreenhouseScraper',
    slug: 'burnt',
    homepage: 'https://xion.burnt.com',
  },
  {
    name: 'Calendly',
    scraper: 'GreenhouseScraper',
    slug: 'calendly',
    domains: ['careers.calendly.com'],
    homepage: 'https://calendly.com',
  },
  {
    name: 'California Academy of Sciences',
    scraper: 'GreenhouseScraper',
    slug: 'californiaacademyofsciences',
    homepage: 'https://www.calacademy.org',
  },
  {
    name: 'Canva',
    scraper: 'SmartRecruitersScraper',
    slug: 'canva',
    domains: ['careers.canva.com'],
    homepage: 'http://www.canva.com',
  },
  {
    name: 'Carta',
    scraper: 'GreenhouseScraper',
    slug: 'carta',
    homepage: 'https://carta.com',
  },
  {
    name: 'Cartesia',
    scraper: 'AshbyScraper',
    slug: 'cartesia',
    homepage: 'https://cartesia.ai',
  },
  {
    name: 'Chalk',
    scraper: 'AshbyScraper',
    slug: 'chalk',
    homepage: 'https://chalk.ai',
  },
  {
    name: 'Chan Zuckerberg Biohub',
    scraper: 'GreenhouseScraper',
    slug: 'biohub',
    homepage: 'https://biohub.org',
  },
  {
    name: 'Checkr',
    scraper: 'GreenhouseScraper',
    slug: 'checkr',
    homepage: 'https://checkr.com',
  },
  {
    name: 'Chime',
    scraper: 'GreenhouseScraper',
    slug: 'chime',
    domains: ['careers.chime.com'],
    homepage: 'https://chime.com',
  },
  {
    name: 'City and County of San Francisco',
    scraper: 'SmartRecruitersScraper',
    slug: 'CityAndCountyOfSanFrancisco1',
    homepage: 'https://www.sf.gov',
  },
  {
    name: 'Clay',
    scraper: 'AshbyScraper',
    slug: 'claylabs',
    homepage: 'https://www.clay.com',
  },
  {
    name: 'ClickHouse',
    scraper: 'AshbyScraper',
    slug: 'clickhouse',
    domains: ['careers.clickhouse.com'],
    homepage: 'https://clickhouse.com',
  },
  {
    name: 'Cloudflare',
    scraper: 'GreenhouseScraper',
    slug: 'cloudflare',
    homepage: 'https://www.cloudflare.com',
  },
  {
    name: 'Cockroach Labs',
    scraper: 'GreenhouseScraper',
    slug: 'cockroachlabs',
    homepage: 'https://www.cockroachlabs.com',
  },
  {
    name: 'Cohere',
    scraper: 'AshbyScraper',
    slug: 'cohere',
    homepage: 'https://cohere.com',
  },
  {
    name: 'Coinbase',
    scraper: 'GreenhouseScraper',
    slug: 'coinbase',
    domains: ['careers.coinbase.com'],
    homepage: 'https://www.coinbase.com',
  },
  {
    name: 'Collective',
    scraper: 'AshbyScraper',
    slug: 'collective',
    homepage: 'https://www.collective.com',
  },
  {
    name: 'Compa',
    scraper: 'AshbyScraper',
    slug: 'compa',
    homepage: 'http://compa.ai',
  },
  {
    name: 'Composio',
    scraper: 'AshbyScraper',
    slug: 'composio',
    homepage: 'https://composio.dev',
  },
  {
    name: 'Console',
    scraper: 'AshbyScraper',
    slug: 'console',
    domains: ['careers.console.com'],
    homepage: 'https://www.console.co',
  },
  {
    name: 'Convex',
    scraper: 'AshbyScraper',
    slug: 'convex-dev',
    homepage: 'https://convex.dev',
  },
  {
    name: 'CoreWeave',
    scraper: 'GreenhouseScraper',
    slug: 'coreweave',
    homepage: 'https://coreweave.com',
  },
  {
    name: 'Coupang',
    scraper: 'GreenhouseScraper',
    slug: 'coupang',
    homepage: 'https://www.coupang.com',
  },
  {
    name: 'CRB',
    scraper: 'SmartRecruitersScraper',
    slug: 'crb',
    homepage: 'https://www.crbgroup.com',
  },
  {
    name: 'CrewAI',
    scraper: 'WorkableScraper',
    slug: 'crewai',
    homepage: 'https://crewai.com',
  },
  {
    name: 'Crosby',
    scraper: 'AshbyScraper',
    slug: 'crosby',
    homepage: 'https://crosby.ai',
  },
  {
    name: 'Crusoe',
    scraper: 'AshbyScraper',
    slug: 'crusoe',
    homepage: 'https://crusoe.ai',
  },
  {
    name: 'Cursor',
    scraper: 'AshbyScraper',
    slug: 'cursor',
    homepage: 'https://cursor.com',
  },
  {
    name: 'Databricks',
    scraper: 'GreenhouseScraper',
    slug: 'databricks',
    homepage: 'https://www.databricks.com',
  },
  {
    name: 'Datadog',
    scraper: 'GreenhouseScraper',
    slug: 'datadog',
    homepage: 'https://www.datadoghq.com',
  },
  {
    name: 'David AI',
    scraper: 'AshbyScraper',
    slug: 'david-ai',
    homepage: 'https://www.withdavid.ai',
  },
  {
    name: 'Decagon',
    scraper: 'AshbyScraper',
    slug: 'decagon',
    homepage: 'https://decagon.ai',
  },
  {
    name: 'Discord',
    scraper: 'GreenhouseScraper',
    slug: 'discord',
    homepage: 'https://discord.com',
  },
  {
    name: 'Docker',
    scraper: 'AshbyScraper',
    slug: 'docker',
    homepage: 'https://docker.com',
  },
  {
    name: 'DoorDash',
    scraper: 'GreenhouseScraper',
    slug: 'doordashusa',
    domains: ['careers.doordash.com'],
    homepage: 'https://www.doordash.com',
  },
  {
    name: 'Drata',
    scraper: 'AshbyScraper',
    slug: 'drata',
    homepage: 'https://drata.com',
  },
  {
    name: 'Dropbox',
    scraper: 'GreenhouseScraper',
    slug: 'dropbox',
    homepage: 'https://www.dropbox.com',
  },
  {
    name: 'Duolingo',
    scraper: 'GreenhouseScraper',
    slug: 'duolingo',
    domains: ['careers.duolingo.com'],
    homepage: 'https://www.duolingo.com',
  },
  {
    name: 'Dust',
    scraper: 'AshbyScraper',
    slug: 'dust',
    homepage: 'https://dust.tt',
  },
  {
    name: 'E2B',
    scraper: 'AshbyScraper',
    slug: 'e2b',
    homepage: 'https://www.e2b.dev',
  },
  {
    name: 'Elastic',
    scraper: 'GreenhouseScraper',
    slug: 'elastic',
    homepage: 'https://www.elastic.co',
  },
  {
    name: 'ElevenLabs',
    scraper: 'AshbyScraper',
    slug: 'elevenlabs',
    homepage: 'https://elevenlabs.io',
  },
  {
    name: 'Elicit',
    scraper: 'AshbyScraper',
    slug: 'elicit',
    homepage: 'https://elicit.com',
  },
  {
    name: 'EliseAI',
    scraper: 'AshbyScraper',
    slug: 'eliseai',
    homepage: 'https://eliseai.com',
  },
  {
    name: 'Epic Games',
    scraper: 'GreenhouseScraper',
    slug: 'epicgames',
    domains: ['careers.epicgames.com'],
    homepage: 'https://www.epicgames.com',
  },
  {
    name: 'Exa Labs',
    scraper: 'AshbyScraper',
    slug: 'exa',
    homepage: 'https://exa.ai',
  },
  {
    name: 'Faire',
    scraper: 'GreenhouseScraper',
    slug: 'faire',
    domains: ['careers.faire.com'],
    homepage: 'https://www.faire.com',
  },
  {
    name: 'fal',
    scraper: 'AshbyScraper',
    slug: 'fal-ai',
    homepage: 'https://fal.ai',
  },
  {
    name: 'Figma',
    scraper: 'GreenhouseScraper',
    slug: 'figma',
    homepage: 'https://www.figma.com',
  },
  {
    name: 'Fireworks AI',
    scraper: 'AshbyScraper',
    slug: 'fireworks',
    homepage: 'https://fireworks.ai',
  },
  {
    name: 'Flexport',
    scraper: 'GreenhouseScraper',
    slug: 'flexport',
    homepage: 'https://www.flexport.com',
  },
  {
    name: 'Flock Safety',
    scraper: 'AshbyScraper',
    slug: 'Flock Safety',
    homepage: 'https://www.flocksafety.com',
  },
  {
    name: 'Fluidstack',
    scraper: 'AshbyScraper',
    slug: 'fluidstack',
    homepage: 'https://www.fluidstack.io',
  },
  {
    name: 'Freed',
    scraper: 'AshbyScraper',
    slug: 'freed',
    homepage: 'https://www.getfreed.ai',
  },
  {
    name: 'Freenome',
    scraper: 'GreenhouseScraper',
    slug: 'freenome',
    domains: ['careers.freenome.com'],
    homepage: 'https://www.freenome.com',
  },
  {
    name: 'Gamma',
    scraper: 'AshbyScraper',
    slug: 'gamma',
    homepage: 'https://gamma.app',
  },
  {
    name: 'Gap Inc.',
    scraper: 'WorkdayScraper',
    slug: 'gapinc.wd1.GAPINC',
    homepage: 'https://www.gapinc.com',
  },
  {
    name: 'Genentech',
    scraper: 'WorkdayScraper',
    slug: 'roche.wd3.ROG-A2O-GENE',
    homepage: 'https://www.gene.com',
  },
  {
    name: 'Genius AI',
    scraper: 'AshbyScraper',
    slug: 'geniusai',
    homepage: 'https://genius.ai',
  },
  {
    name: 'Gilead Sciences',
    scraper: 'WorkdayScraper',
    slug: 'gilead.wd1.gileadcareers',
    homepage: 'https://www.gilead.com',
  },
  {
    name: 'GitHub',
    scraper: 'GitHubScraper',
    slug: 'github',
    homepage: 'https://github.com',
  },
  {
    name: 'GitLab',
    scraper: 'GreenhouseScraper',
    slug: 'gitlab',
    homepage: 'https://about.gitlab.com',
  },
  {
    name: 'Gladstone Institutes',
    scraper: 'WorkdayScraper',
    slug: 'gladstone.wd503.careers',
    homepage: 'https://gladstone.org',
  },
  {
    name: 'Glean',
    scraper: 'GreenhouseScraper',
    slug: 'gleanwork',
    homepage: 'https://www.glean.com',
  },
  {
    name: 'Gong',
    scraper: 'GreenhouseScraper',
    slug: 'gongio',
    homepage: 'https://www.gong.io',
  },
  {
    name: 'Google',
    scraper: 'GoogleScraper',
    slug: 'google',
    homepage: 'https://www.google.com',
  },
  {
    name: 'Granola',
    scraper: 'AshbyScraper',
    slug: 'granola',
    homepage: 'https://www.granola.ai',
  },
  {
    name: 'Guardant Health',
    scraper: 'WorkdayScraper',
    slug: 'gh.wd1.gh',
    homepage: 'https://guardanthealth.com',
  },
  {
    name: 'Gusto',
    scraper: 'GreenhouseScraper',
    slug: 'gusto',
    domains: ['careers.gusto.com'],
    homepage: 'https://gusto.com',
  },
  {
    name: 'Harmonic',
    scraper: 'AshbyScraper',
    slug: 'harmonic',
    homepage: 'https://harmonic.fun',
  },
  {
    name: 'Harvey',
    scraper: 'AshbyScraper',
    slug: 'harvey',
    homepage: 'https://www.harvey.ai',
  },
  {
    name: 'Hightouch',
    scraper: 'GreenhouseScraper',
    slug: 'hightouch',
    homepage: 'https://hightouch.com',
  },
  {
    name: 'Hyperspell',
    scraper: 'AshbyScraper',
    slug: 'hyperspell',
    homepage: 'https://hyperspell.com',
  },
  {
    name: 'ICON',
    scraper: 'WorkdayScraper',
    slug: 'icon.wd3.broadbean_external',
    homepage: 'https://www.iconplc.com',
  },
  {
    name: 'Idler',
    scraper: 'AshbyScraper',
    slug: 'idler',
    homepage: 'https://idler.ai',
  },
  {
    name: 'Instacart',
    scraper: 'GreenhouseScraper',
    slug: 'instacart',
    homepage: 'https://www.instacart.com',
  },
  {
    name: 'Invert',
    scraper: 'AshbyScraper',
    slug: 'invert',
    homepage: 'https://invertbio.com',
  },
  {
    name: 'IonQ',
    scraper: 'GreenhouseScraper',
    slug: 'ionq',
    homepage: 'https://ionq.com',
  },
  {
    name: 'January',
    scraper: 'AshbyScraper',
    slug: 'january',
    domains: ['careers.january.com'],
    homepage: 'https://january.com',
  },
  {
    name: 'Juicebox',
    scraper: 'AshbyScraper',
    slug: 'juicebox',
    homepage: 'https://juicebox.ai',
  },
  {
    name: 'Kinelo',
    scraper: 'GreenhouseScraper',
    slug: 'kinelo',
    homepage: 'https://www.kinelo.com',
  },
  {
    name: 'Lattice',
    scraper: 'GreenhouseScraper',
    slug: 'lattice',
    homepage: 'https://lattice.com',
  },
  {
    name: 'Legora',
    scraper: 'AshbyScraper',
    slug: 'legora',
    homepage: 'https://legora.com',
  },
  {
    name: 'Levi Strauss & Co.',
    scraper: 'WorkdayScraper',
    slug: 'levistraussandco.wd5.External',
    homepage: 'https://www.levistrauss.com',
  },
  {
    name: 'Linear',
    scraper: 'AshbyScraper',
    slug: 'linear',
    homepage: 'https://linear.app',
  },
  {
    name: 'Listen Labs',
    scraper: 'AshbyScraper',
    slug: 'listenlabs',
    homepage: 'https://www.listenlabs.ai',
  },
  {
    name: 'LlamaIndex',
    scraper: 'AshbyScraper',
    slug: 'llamaindex',
    homepage: 'https://www.llamaindex.ai',
  },
  {
    name: 'Lovable',
    scraper: 'AshbyScraper',
    slug: 'lovable',
    homepage: 'https://lovable.dev',
  },
  {
    name: 'Lyft',
    scraper: 'GreenhouseScraper',
    slug: 'lyft',
    homepage: 'https://www.lyft.com',
  },
  {
    name: 'Magical',
    scraper: 'AshbyScraper',
    slug: 'magical',
    homepage: 'http://getmagical.com',
  },
  {
    name: 'Marble',
    scraper: 'AshbyScraper',
    slug: 'marble',
    homepage: 'https://marble.studio',
  },
  {
    name: 'Metriport',
    scraper: 'AshbyScraper',
    slug: 'metriport',
    homepage: 'https://metriport.com',
  },
  {
    name: 'MillerKnoll',
    scraper: 'WorkdayScraper',
    slug: 'millerknoll.wd1.MillerKnoll',
    homepage: 'https://www.millerknoll.com',
  },
  {
    name: 'Mintlify',
    scraper: 'AshbyScraper',
    slug: 'mintlify',
    homepage: 'https://mintlify.com',
  },
  {
    name: 'MintMCP',
    scraper: 'AshbyScraper',
    slug: 'mintmcp',
    homepage: 'https://www.mintmcp.com',
  },
  {
    name: 'Miro',
    scraper: 'AshbyScraper',
    slug: 'miro',
    homepage: 'https://miro.com',
  },
  {
    name: 'Mixpanel',
    scraper: 'GreenhouseScraper',
    slug: 'mixpanel',
    homepage: 'https://mixpanel.com',
  },
  {
    name: 'Modal',
    scraper: 'AshbyScraper',
    slug: 'modal',
    homepage: 'https://modal.com',
  },
  {
    name: 'Modern Treasury',
    scraper: 'AshbyScraper',
    slug: 'moderntreasury',
    homepage: 'https://www.moderntreasury.com',
  },
  {
    name: 'MongoDB',
    scraper: 'GreenhouseScraper',
    slug: 'mongodb',
    domains: ['careers.mongodb.com'],
    homepage: 'https://www.mongodb.com',
  },
  {
    name: 'Mozilla',
    scraper: 'GreenhouseScraper',
    slug: 'mozilla',
    domains: ['careers.mozilla.com'],
    homepage: 'https://www.mozilla.org',
  },
  {
    name: 'n8n',
    scraper: 'AshbyScraper',
    slug: 'n8n',
    homepage: 'https://n8n.io',
  },
  {
    name: 'NetEase',
    scraper: 'AshbyScraper',
    slug: 'netease',
    homepage: 'https://www.163.com',
  },
  {
    name: 'Netflix',
    scraper: 'NetflixScraper',
    slug: 'netflix',
    homepage: 'https://www.netflix.com',
  },
  {
    name: 'Netlify',
    scraper: 'GreenhouseScraper',
    slug: 'netlify',
    homepage: 'https://www.netlify.com',
  },
  {
    name: 'Neuralink',
    scraper: 'GreenhouseScraper',
    slug: 'neuralink',
    homepage: 'https://neuralink.com',
  },
  {
    name: 'Nooks',
    scraper: 'AshbyScraper',
    slug: 'nooks',
    homepage: 'https://www.nooks.ai',
  },
  {
    name: 'Notion',
    scraper: 'AshbyScraper',
    slug: 'notion',
    homepage: 'https://www.notion.com',
  },
  {
    name: 'Nudge',
    scraper: 'AshbyScraper',
    slug: 'nudge',
    homepage: 'https://www.nudge.com',
  },
  {
    name: 'Numeric',
    scraper: 'AshbyScraper',
    slug: 'numeric',
    homepage: 'https://www.numeric.io',
  },
  {
    name: 'Nuna Inc.',
    scraper: 'AshbyScraper',
    slug: 'nuna',
    homepage: 'https://www.nuna.com',
  },
  {
    name: 'NVIDIA',
    scraper: 'NvidiaScraper',
    slug: 'nvidia',
    domains: ['careers.nvidia.com'],
    homepage: 'https://www.nvidia.com',
  },
  {
    name: 'Okta',
    scraper: 'GreenhouseScraper',
    slug: 'okta',
    homepage: 'https://www.okta.com',
  },
  {
    name: 'OpenAI',
    scraper: 'AshbyScraper',
    slug: 'openai',
    homepage: 'https://openai.com',
  },
  {
    name: 'OpenEvidence',
    scraper: 'AshbyScraper',
    slug: 'openevidence',
    homepage: 'https://www.openevidence.com',
  },
  {
    name: 'OpenRouter',
    scraper: 'AshbyScraper',
    slug: 'openrouter',
    homepage: 'https://openrouter.ai',
  },
  {
    name: 'PagerDuty',
    scraper: 'GreenhouseScraper',
    slug: 'pagerduty',
    homepage: 'https://www.pagerduty.com',
  },
  {
    name: 'Parallel Web Systems',
    scraper: 'AshbyScraper',
    slug: 'parallel',
    homepage: 'http://parallel.ai',
  },
  {
    name: 'Peloton',
    scraper: 'GreenhouseScraper',
    slug: 'peloton',
    homepage: 'https://www.onepeloton.com',
  },
  {
    name: 'Perplexity',
    scraper: 'AshbyScraper',
    slug: 'perplexity',
    domains: ['careers.perplexity.com'],
    homepage: 'https://www.perplexity.ai',
  },
  {
    name: 'Pinterest',
    scraper: 'GreenhouseScraper',
    slug: 'pinterest',
    domains: ['pinterestcareers.com'],
    homepage: 'https://www.pinterest.com',
  },
  {
    name: 'Plaid',
    scraper: 'AshbyScraper',
    slug: 'plaid',
    homepage: 'https://plaid.com',
  },
  {
    name: 'PlanetScale',
    scraper: 'GreenhouseScraper',
    slug: 'planetscale',
    homepage: 'https://planetscale.com',
  },
  {
    name: 'Plaud',
    scraper: 'AshbyScraper',
    slug: 'plaud',
    homepage: 'http://plaud.ai',
  },
  {
    name: 'PostHog',
    scraper: 'AshbyScraper',
    slug: 'posthog',
    homepage: 'https://posthog.com',
  },
  {
    name: 'Postman',
    scraper: 'GreenhouseScraper',
    slug: 'postman',
    homepage: 'https://www.postman.com',
  },
  {
    name: 'Pure Storage',
    scraper: 'GreenhouseScraper',
    slug: 'purestorage',
    homepage: 'https://www.purestorage.com',
  },
  {
    name: 'Pylon',
    scraper: 'AshbyScraper',
    slug: 'pylon',
    homepage: 'https://www.pylonlending.com',
  },
  {
    name: 'Quora',
    scraper: 'AshbyScraper',
    slug: 'quora',
    domains: ['careers.quora.com'],
    homepage: 'https://quora.com',
  },
  {
    name: 'Ramp',
    scraper: 'AshbyScraper',
    slug: 'ramp',
    homepage: 'https://ramp.com',
  },
  {
    name: 'Rapt Studio',
    scraper: 'LeverScraper',
    slug: 'RaptStudio',
    homepage: 'https://raptstudio.com',
  },
  {
    name: 'Reddit',
    scraper: 'GreenhouseScraper',
    slug: 'reddit',
    homepage: 'https://www.reddit.com',
  },
  {
    name: 'Replit',
    scraper: 'AshbyScraper',
    slug: 'replit',
    domains: ['careers.replit.com'],
    homepage: 'http://replit.com',
  },
  {
    name: 'Resend',
    scraper: 'AshbyScraper',
    slug: 'resend',
    homepage: 'https://resend.com',
  },
  {
    name: 'Retell AI',
    scraper: 'AshbyScraper',
    slug: 'retell-ai',
    domains: ['careers.retellai.com'],
    homepage: 'https://www.retellai.com',
  },
  {
    name: 'Rillet',
    scraper: 'AshbyScraper',
    slug: 'rillet',
    homepage: 'https://www.rillet.com',
  },
  {
    name: 'Rippling',
    scraper: 'RipplingScraper',
    slug: 'rippling',
    homepage: 'https://www.rippling.com',
  },
  {
    name: 'Robinhood',
    scraper: 'GreenhouseScraper',
    slug: 'robinhood',
    domains: ['careers.robinhood.com'],
    homepage: 'https://robinhood.com',
  },
  {
    name: 'Roblox',
    scraper: 'GreenhouseScraper',
    slug: 'roblox',
    domains: ['careers.roblox.com'],
    homepage: 'https://www.roblox.com',
  },
  {
    name: 'Roku',
    scraper: 'GreenhouseScraper',
    slug: 'roku',
    homepage: 'https://www.roku.com',
  },
  {
    name: 'Runway',
    scraper: 'AshbyScraper',
    slug: 'runway',
    homepage: 'https://runway.com',
  },
  {
    name: 'Samsara',
    scraper: 'GreenhouseScraper',
    slug: 'samsara',
    homepage: 'https://www.samsara.com',
  },
  {
    name: 'Scale AI',
    scraper: 'GreenhouseScraper',
    slug: 'scaleai',
    homepage: 'https://scale.com',
  },
  {
    name: 'Sentry',
    scraper: 'AshbyScraper',
    slug: 'sentry',
    domains: ['sentrycareers.com'],
    homepage: 'https://sentry.io',
  },
  {
    name: 'Serval',
    scraper: 'AshbyScraper',
    slug: 'serval',
    homepage: 'https://www.serval.com',
  },
  {
    name: 'SFMOMA',
    scraper: 'LeverScraper',
    slug: 'sfmoma',
    homepage: 'https://www.sfmoma.org',
  },
  {
    name: 'Shopify',
    scraper: 'ShopifyScraper',
    slug: 'shopify',
    domains: ['careers.shopify.com'],
    homepage: 'https://www.shopify.com',
  },
  {
    name: 'Sierra',
    scraper: 'AshbyScraper',
    slug: 'sierra',
    homepage: 'https://sierra.ai',
  },
  {
    name: 'Sift',
    scraper: 'AshbyScraper',
    slug: 'sift',
    domains: ['siftcareers.com'],
    homepage: 'https://sift.com',
  },
  {
    name: 'Skidmore, Owings & Merrill',
    scraper: 'WorkdayScraper',
    slug: 'som.wd5.External',
    homepage: 'https://www.som.com',
  },
  {
    name: 'Slack',
    scraper: 'WorkdayScraper',
    slug: 'salesforce.wd12.Slack',
    domains: ['careers.slack.com'],
    homepage: 'https://slack.com',
  },
  {
    name: 'Snowflake',
    scraper: 'AshbyScraper',
    slug: 'snowflake',
    domains: ['careers.snowflake.com'],
    homepage: 'https://www.snowflake.com',
  },
  {
    name: 'SoFi',
    scraper: 'GreenhouseScraper',
    slug: 'sofi',
    homepage: 'https://www.sofi.com',
  },
  {
    name: 'SpaceX',
    scraper: 'GreenhouseScraper',
    slug: 'spacex',
    homepage: 'https://www.spacex.com',
  },
  {
    name: 'Span',
    scraper: 'AshbyScraper',
    slug: 'span',
    homepage: 'https://www.span.io',
  },
  {
    name: 'Spotify',
    scraper: 'LeverScraper',
    slug: 'spotify',
    homepage: 'https://www.spotify.com',
  },
  {
    name: 'Sprig',
    scraper: 'AshbyScraper',
    slug: 'sprig',
    homepage: 'https://www.sprig.com',
  },
  {
    name: 'Squarespace',
    scraper: 'GreenhouseScraper',
    slug: 'squarespace',
    domains: ['careers.squarespace.com'],
    homepage: 'https://www.squarespace.com',
  },
  {
    name: 'Stripe',
    scraper: 'GreenhouseScraper',
    slug: 'stripe',
    homepage: 'https://stripe.com',
  },
  {
    name: 'Supabase',
    scraper: 'AshbyScraper',
    slug: 'supabase',
    homepage: 'https://supabase.com',
  },
  {
    name: 'Sydecar',
    scraper: 'AshbyScraper',
    slug: 'sydecar',
    homepage: 'https://www.sydecar.io',
  },
  {
    name: 'Tailscale',
    scraper: 'GreenhouseScraper',
    slug: 'tailscale',
    homepage: 'https://tailscale.com',
  },
  {
    name: 'Temporal',
    scraper: 'AshbyScraper',
    slug: 'temporal',
    homepage: 'https://temporal.io',
  },
  {
    name: 'Thumbtack',
    scraper: 'AshbyScraper',
    slug: 'thumbtack',
    domains: ['careers.thumbtack.com'],
    homepage: 'https://www.thumbtack.com',
  },
  {
    name: 'Together AI',
    scraper: 'GreenhouseScraper',
    slug: 'togetherai',
    homepage: 'https://www.together.ai',
  },
  {
    name: 'turbopuffer',
    scraper: 'AshbyScraper',
    slug: 'turbopuffer',
    homepage: 'https://turbopuffer.com',
  },
  {
    name: 'Twilio',
    scraper: 'GreenhouseScraper',
    slug: 'twilio',
    homepage: 'https://www.twilio.com',
  },
  {
    name: 'Twitch',
    scraper: 'GreenhouseScraper',
    slug: 'twitch',
    homepage: 'http://www.twitch.tv',
  },
  {
    name: 'Uber',
    scraper: 'UberScraper',
    slug: 'uber',
    domains: ['jobs.uber.com'],
    homepage: 'https://www.uber.com',
  },
  {
    name: 'Unify',
    scraper: 'AshbyScraper',
    slug: 'unify',
    homepage: 'https://unifygtm.com',
  },
  {
    name: 'UserTesting',
    scraper: 'WorkdayScraper',
    slug: 'usertesting.wd12.UserTesting',
    homepage: 'https://www.usertesting.com',
  },
  {
    name: 'Valon',
    scraper: 'AshbyScraper',
    slug: 'valon',
    homepage: 'https://www.valon.ai',
  },
  {
    name: 'Vanta',
    scraper: 'AshbyScraper',
    slug: 'vanta',
    homepage: 'https://vanta.com',
  },
  {
    name: 'Vercel',
    scraper: 'GreenhouseScraper',
    slug: 'vercel',
    homepage: 'https://vercel.com',
  },
  {
    name: 'Verily',
    scraper: 'WorkdayScraper',
    slug: 'verily.wd1.Verily_Careers',
    homepage: 'https://verily.com',
  },
  {
    name: 'Waymo',
    scraper: 'GreenhouseScraper',
    slug: 'waymo',
    homepage: 'https://waymo.com',
  },
  {
    name: 'Webflow',
    scraper: 'GreenhouseScraper',
    slug: 'webflow',
    homepage: 'https://webflow.com',
  },
  {
    name: 'Weekend',
    scraper: 'AshbyScraper',
    slug: 'weekend',
    homepage: 'https://www.weekend.com',
  },
  {
    name: 'Wispr Flow',
    scraper: 'AshbyScraper',
    slug: 'wispr-flow',
    homepage: 'https://wisprflow.ai',
  },
  {
    name: 'Workato',
    scraper: 'GreenhouseScraper',
    slug: 'workato',
    homepage: 'https://www.workato.com',
  },
  {
    name: 'xAI',
    scraper: 'GreenhouseScraper',
    slug: 'xai',
    homepage: 'https://x.ai',
  },
  {
    name: 'XBOW',
    scraper: 'AshbyScraper',
    slug: 'xbowcareers',
    homepage: 'https://xbow.com',
  },
  {
    name: 'Zapier',
    scraper: 'AshbyScraper',
    slug: 'zapier',
    homepage: 'https://zapier.com',
  },
  {
    name: 'Zip',
    scraper: 'AshbyScraper',
    slug: 'zip',
    homepage: 'https://ziphq.com',
  },
  {
    name: 'Zscaler',
    scraper: 'GreenhouseScraper',
    slug: 'zscaler',
    homepage: 'https://www.zscaler.com',
  },
];
