import { type Company } from './companies.ts';

/**
 * The companies this package already knows how to scrape. On first run this
 * list is copied to `~/.job-scraper/companies.json`, which then takes over as
 * the live registry; companies resolved at runtime get appended there
 * rather than here, so this file only needs updating when a scraper is added.
 */
export const seedCompanies: Company[] = [
  {
    name: 'Abnormal AI',
    scraper: 'GreenhouseScraper',
    slug: 'abnormalsecurity',
  },
  { name: 'Affirm', scraper: 'GreenhouseScraper', slug: 'affirm' },
  {
    name: 'Airbnb',
    scraper: 'GreenhouseScraper',
    slug: 'airbnb',
    domains: ['careers.airbnb.com'],
  },
  { name: 'Airtable', scraper: 'GreenhouseScraper', slug: 'airtable' },
  { name: 'Amplitude', scraper: 'GreenhouseScraper', slug: 'amplitude' },
  { name: 'Anduril', scraper: 'GreenhouseScraper', slug: 'andurilindustries' },
  { name: 'Anrok', scraper: 'AshbyScraper', slug: 'anrok' },
  { name: 'Anthropic', scraper: 'GreenhouseScraper', slug: 'anthropic' },
  { name: 'Apollo.io', scraper: 'GreenhouseScraper', slug: 'apolloio' },
  { name: 'Applied Compute', scraper: 'AshbyScraper', slug: 'Applied Compute' },
  { name: 'Applied Intuition', scraper: 'AshbyScraper', slug: 'applied' },
  { name: 'AppLovin', scraper: 'GreenhouseScraper', slug: 'applovin' },
  { name: 'Arcade', scraper: 'AshbyScraper', slug: 'arcade-ai' },
  {
    name: 'Arcadia',
    scraper: 'RipplingScraper',
    slug: 'arcadiacareers',
    domains: ['arcadia.com'],
  },
  { name: 'Arena', scraper: 'AshbyScraper', slug: 'arena' },
  { name: 'Artie', scraper: 'AshbyScraper', slug: 'artie' },
  { name: 'Asana', scraper: 'GreenhouseScraper', slug: 'asana' },
  { name: 'Assort Health', scraper: 'AshbyScraper', slug: 'assorthealth' },
  { name: 'Astera Labs', scraper: 'GreenhouseScraper', slug: 'asteralabs' },
  {
    name: 'Autodesk',
    scraper: 'WorkdayScraper',
    slug: 'autodesk.wd1.Ext',
    domains: ['careers.autodesk.com'],
  },
  { name: 'Avoca', scraper: 'AshbyScraper', slug: 'avoca' },
  { name: 'Baseten', scraper: 'AshbyScraper', slug: 'baseten' },
  { name: 'Basis', scraper: 'AshbyScraper', slug: 'basis-ai' },
  { name: 'Block', scraper: 'GreenhouseScraper', slug: 'block' },
  { name: 'Braintrust', scraper: 'AshbyScraper', slug: 'braintrust' },
  {
    name: 'Brex',
    scraper: 'GreenhouseScraper',
    slug: 'brex',
    domains: ['careers.brex.com'],
  },
  { name: 'Browserbase', scraper: 'AshbyScraper', slug: 'browserbase' },
  { name: 'Buildkite', scraper: 'GreenhouseScraper', slug: 'buildkite' },
  { name: 'Burnt', scraper: 'GreenhouseScraper', slug: 'burnt' },
  {
    name: 'Calendly',
    scraper: 'GreenhouseScraper',
    slug: 'calendly',
    domains: ['careers.calendly.com'],
  },
  {
    name: 'California Academy of Sciences',
    scraper: 'GreenhouseScraper',
    slug: 'californiaacademyofsciences',
  },
  {
    name: 'Canva',
    scraper: 'SmartRecruitersScraper',
    slug: 'canva',
    domains: ['careers.canva.com'],
  },
  { name: 'Carta', scraper: 'GreenhouseScraper', slug: 'carta' },
  { name: 'Cartesia', scraper: 'AshbyScraper', slug: 'cartesia' },
  { name: 'Chalk', scraper: 'AshbyScraper', slug: 'chalk' },
  {
    name: 'Chan Zuckerberg Biohub',
    scraper: 'GreenhouseScraper',
    slug: 'biohub',
  },
  { name: 'Checkr', scraper: 'GreenhouseScraper', slug: 'checkr' },
  {
    name: 'Chime',
    scraper: 'GreenhouseScraper',
    slug: 'chime',
    domains: ['careers.chime.com'],
  },
  {
    name: 'City and County of San Francisco',
    scraper: 'SmartRecruitersScraper',
    slug: 'CityAndCountyOfSanFrancisco1',
  },
  { name: 'Clay', scraper: 'AshbyScraper', slug: 'claylabs' },
  {
    name: 'ClickHouse',
    scraper: 'AshbyScraper',
    slug: 'clickhouse',
    domains: ['careers.clickhouse.com'],
  },
  { name: 'Cloudflare', scraper: 'GreenhouseScraper', slug: 'cloudflare' },
  {
    name: 'Cockroach Labs',
    scraper: 'GreenhouseScraper',
    slug: 'cockroachlabs',
  },
  { name: 'Cohere', scraper: 'AshbyScraper', slug: 'cohere' },
  {
    name: 'Coinbase',
    scraper: 'GreenhouseScraper',
    slug: 'coinbase',
    domains: ['careers.coinbase.com'],
  },
  { name: 'Collective', scraper: 'AshbyScraper', slug: 'collective' },
  { name: 'Compa', scraper: 'AshbyScraper', slug: 'compa' },
  { name: 'Composio', scraper: 'AshbyScraper', slug: 'composio' },
  {
    name: 'Console',
    scraper: 'AshbyScraper',
    slug: 'console',
    domains: ['careers.console.com'],
  },
  { name: 'Convex', scraper: 'AshbyScraper', slug: 'convex-dev' },
  { name: 'CoreWeave', scraper: 'GreenhouseScraper', slug: 'coreweave' },
  { name: 'Coupang', scraper: 'GreenhouseScraper', slug: 'coupang' },
  { name: 'CRB', scraper: 'SmartRecruitersScraper', slug: 'crb' },
  { name: 'CrewAI', scraper: 'WorkableScraper', slug: 'crewai' },
  { name: 'Crosby', scraper: 'AshbyScraper', slug: 'crosby' },
  { name: 'Crusoe', scraper: 'AshbyScraper', slug: 'crusoe' },
  { name: 'Cursor', scraper: 'AshbyScraper', slug: 'cursor' },
  { name: 'Databricks', scraper: 'GreenhouseScraper', slug: 'databricks' },
  { name: 'Datadog', scraper: 'GreenhouseScraper', slug: 'datadog' },
  { name: 'David AI', scraper: 'AshbyScraper', slug: 'david-ai' },
  { name: 'Decagon', scraper: 'AshbyScraper', slug: 'decagon' },
  { name: 'Discord', scraper: 'GreenhouseScraper', slug: 'discord' },
  { name: 'Docker', scraper: 'AshbyScraper', slug: 'docker' },
  {
    name: 'DoorDash',
    scraper: 'GreenhouseScraper',
    slug: 'doordashusa',
    domains: ['careers.doordash.com'],
  },
  { name: 'Drata', scraper: 'AshbyScraper', slug: 'drata' },
  { name: 'Dropbox', scraper: 'GreenhouseScraper', slug: 'dropbox' },
  {
    name: 'Duolingo',
    scraper: 'GreenhouseScraper',
    slug: 'duolingo',
    domains: ['careers.duolingo.com'],
  },
  { name: 'Dust', scraper: 'AshbyScraper', slug: 'dust' },
  { name: 'E2B', scraper: 'AshbyScraper', slug: 'e2b' },
  { name: 'Elastic', scraper: 'GreenhouseScraper', slug: 'elastic' },
  { name: 'ElevenLabs', scraper: 'AshbyScraper', slug: 'elevenlabs' },
  { name: 'Elicit', scraper: 'AshbyScraper', slug: 'elicit' },
  { name: 'EliseAI', scraper: 'AshbyScraper', slug: 'eliseai' },
  {
    name: 'Epic Games',
    scraper: 'GreenhouseScraper',
    slug: 'epicgames',
    domains: ['careers.epicgames.com'],
  },
  { name: 'Exa Labs', scraper: 'AshbyScraper', slug: 'exa' },
  {
    name: 'Faire',
    scraper: 'GreenhouseScraper',
    slug: 'faire',
    domains: ['careers.faire.com'],
  },
  { name: 'fal', scraper: 'AshbyScraper', slug: 'fal-ai' },
  { name: 'Figma', scraper: 'GreenhouseScraper', slug: 'figma' },
  { name: 'Fireworks AI', scraper: 'AshbyScraper', slug: 'fireworks' },
  { name: 'Flexport', scraper: 'GreenhouseScraper', slug: 'flexport' },
  { name: 'Flock Safety', scraper: 'AshbyScraper', slug: 'Flock Safety' },
  { name: 'Fluidstack', scraper: 'AshbyScraper', slug: 'fluidstack' },
  { name: 'Freed', scraper: 'AshbyScraper', slug: 'freed' },
  {
    name: 'Freenome',
    scraper: 'GreenhouseScraper',
    slug: 'freenome',
    domains: ['careers.freenome.com'],
  },
  { name: 'Gamma', scraper: 'AshbyScraper', slug: 'gamma' },
  { name: 'Gap Inc.', scraper: 'WorkdayScraper', slug: 'gapinc.wd1.GAPINC' },
  {
    name: 'Genentech',
    scraper: 'WorkdayScraper',
    slug: 'roche.wd3.ROG-A2O-GENE',
  },
  { name: 'Genius AI', scraper: 'AshbyScraper', slug: 'geniusai' },
  {
    name: 'Gilead Sciences',
    scraper: 'WorkdayScraper',
    slug: 'gilead.wd1.gileadcareers',
  },
  { name: 'GitHub', scraper: 'GitHubScraper', slug: 'github' },
  { name: 'GitLab', scraper: 'GreenhouseScraper', slug: 'gitlab' },
  {
    name: 'Gladstone Institutes',
    scraper: 'WorkdayScraper',
    slug: 'gladstone.wd503.careers',
  },
  { name: 'Glean', scraper: 'GreenhouseScraper', slug: 'gleanwork' },
  { name: 'Gong', scraper: 'GreenhouseScraper', slug: 'gongio' },
  { name: 'Google', scraper: 'GoogleScraper', slug: 'google' },
  { name: 'Granola', scraper: 'AshbyScraper', slug: 'granola' },
  { name: 'Guardant Health', scraper: 'WorkdayScraper', slug: 'gh.wd1.gh' },
  {
    name: 'Gusto',
    scraper: 'GreenhouseScraper',
    slug: 'gusto',
    domains: ['careers.gusto.com'],
  },
  { name: 'Harmonic', scraper: 'AshbyScraper', slug: 'harmonic' },
  { name: 'Harvey', scraper: 'AshbyScraper', slug: 'harvey' },
  { name: 'Hightouch', scraper: 'GreenhouseScraper', slug: 'hightouch' },
  { name: 'Hyperspell', scraper: 'AshbyScraper', slug: 'hyperspell' },
  {
    name: 'ICON',
    scraper: 'WorkdayScraper',
    slug: 'icon.wd3.broadbean_external',
  },
  { name: 'Idler', scraper: 'AshbyScraper', slug: 'idler' },
  { name: 'Instacart', scraper: 'GreenhouseScraper', slug: 'instacart' },
  { name: 'Invert', scraper: 'AshbyScraper', slug: 'invert' },
  { name: 'IonQ', scraper: 'GreenhouseScraper', slug: 'ionq' },
  {
    name: 'January',
    scraper: 'AshbyScraper',
    slug: 'january',
    domains: ['careers.january.com'],
  },
  { name: 'Juicebox', scraper: 'AshbyScraper', slug: 'juicebox' },
  { name: 'Kinelo', scraper: 'GreenhouseScraper', slug: 'kinelo' },
  { name: 'Lattice', scraper: 'GreenhouseScraper', slug: 'lattice' },
  { name: 'Legora', scraper: 'AshbyScraper', slug: 'legora' },
  {
    name: 'Levi Strauss & Co.',
    scraper: 'WorkdayScraper',
    slug: 'levistraussandco.wd5.External',
  },
  { name: 'Linear', scraper: 'AshbyScraper', slug: 'linear' },
  { name: 'Listen Labs', scraper: 'AshbyScraper', slug: 'listenlabs' },
  { name: 'LlamaIndex', scraper: 'AshbyScraper', slug: 'llamaindex' },
  { name: 'Lovable', scraper: 'AshbyScraper', slug: 'lovable' },
  { name: 'Lyft', scraper: 'GreenhouseScraper', slug: 'lyft' },
  { name: 'Magical', scraper: 'AshbyScraper', slug: 'magical' },
  { name: 'Marble', scraper: 'AshbyScraper', slug: 'marble' },
  { name: 'Metriport', scraper: 'AshbyScraper', slug: 'metriport' },
  {
    name: 'MillerKnoll',
    scraper: 'WorkdayScraper',
    slug: 'millerknoll.wd1.MillerKnoll',
  },
  { name: 'Mintlify', scraper: 'AshbyScraper', slug: 'mintlify' },
  { name: 'MintMCP', scraper: 'AshbyScraper', slug: 'mintmcp' },
  { name: 'Miro', scraper: 'AshbyScraper', slug: 'miro' },
  { name: 'Mixpanel', scraper: 'GreenhouseScraper', slug: 'mixpanel' },
  { name: 'Modal', scraper: 'AshbyScraper', slug: 'modal' },
  { name: 'Modern Treasury', scraper: 'AshbyScraper', slug: 'moderntreasury' },
  {
    name: 'MongoDB',
    scraper: 'GreenhouseScraper',
    slug: 'mongodb',
    domains: ['careers.mongodb.com'],
  },
  {
    name: 'Mozilla',
    scraper: 'GreenhouseScraper',
    slug: 'mozilla',
    domains: ['careers.mozilla.com'],
  },
  { name: 'n8n', scraper: 'AshbyScraper', slug: 'n8n' },
  { name: 'NetEase', scraper: 'AshbyScraper', slug: 'netease' },
  { name: 'Netflix', scraper: 'NetflixScraper', slug: 'netflix' },
  { name: 'Netlify', scraper: 'GreenhouseScraper', slug: 'netlify' },
  { name: 'Neuralink', scraper: 'GreenhouseScraper', slug: 'neuralink' },
  { name: 'Nooks', scraper: 'AshbyScraper', slug: 'nooks' },
  { name: 'Notion', scraper: 'AshbyScraper', slug: 'notion' },
  { name: 'Nudge', scraper: 'AshbyScraper', slug: 'nudge' },
  { name: 'Numeric', scraper: 'AshbyScraper', slug: 'numeric' },
  { name: 'Nuna Inc.', scraper: 'AshbyScraper', slug: 'nuna' },
  {
    name: 'NVIDIA',
    scraper: 'NvidiaScraper',
    slug: 'nvidia',
    domains: ['careers.nvidia.com'],
  },
  { name: 'Okta', scraper: 'GreenhouseScraper', slug: 'okta' },
  { name: 'OpenAI', scraper: 'AshbyScraper', slug: 'openai' },
  { name: 'OpenEvidence', scraper: 'AshbyScraper', slug: 'openevidence' },
  { name: 'OpenRouter', scraper: 'AshbyScraper', slug: 'openrouter' },
  { name: 'PagerDuty', scraper: 'GreenhouseScraper', slug: 'pagerduty' },
  { name: 'Parallel Web Systems', scraper: 'AshbyScraper', slug: 'parallel' },
  { name: 'Peloton', scraper: 'GreenhouseScraper', slug: 'peloton' },
  {
    name: 'Perplexity',
    scraper: 'AshbyScraper',
    slug: 'perplexity',
    domains: ['careers.perplexity.com'],
  },
  {
    name: 'Pinterest',
    scraper: 'GreenhouseScraper',
    slug: 'pinterest',
    domains: ['pinterestcareers.com'],
  },
  { name: 'Plaid', scraper: 'AshbyScraper', slug: 'plaid' },
  { name: 'PlanetScale', scraper: 'GreenhouseScraper', slug: 'planetscale' },
  { name: 'Plaud', scraper: 'AshbyScraper', slug: 'plaud' },
  { name: 'PostHog', scraper: 'AshbyScraper', slug: 'posthog' },
  { name: 'Postman', scraper: 'GreenhouseScraper', slug: 'postman' },
  { name: 'Pure Storage', scraper: 'GreenhouseScraper', slug: 'purestorage' },
  { name: 'Pylon', scraper: 'AshbyScraper', slug: 'pylon' },
  {
    name: 'Quora',
    scraper: 'AshbyScraper',
    slug: 'quora',
    domains: ['careers.quora.com'],
  },
  { name: 'Ramp', scraper: 'AshbyScraper', slug: 'ramp' },
  { name: 'Rapt Studio', scraper: 'LeverScraper', slug: 'RaptStudio' },
  { name: 'Reddit', scraper: 'GreenhouseScraper', slug: 'reddit' },
  {
    name: 'Replit',
    scraper: 'AshbyScraper',
    slug: 'replit',
    domains: ['careers.replit.com'],
  },
  { name: 'Resend', scraper: 'AshbyScraper', slug: 'resend' },
  {
    name: 'Retell AI',
    scraper: 'AshbyScraper',
    slug: 'retell-ai',
    domains: ['careers.retellai.com'],
  },
  { name: 'Rillet', scraper: 'AshbyScraper', slug: 'rillet' },
  { name: 'Rippling', scraper: 'RipplingScraper', slug: 'rippling' },
  {
    name: 'Robinhood',
    scraper: 'GreenhouseScraper',
    slug: 'robinhood',
    domains: ['careers.robinhood.com'],
  },
  {
    name: 'Roblox',
    scraper: 'GreenhouseScraper',
    slug: 'roblox',
    domains: ['careers.roblox.com'],
  },
  { name: 'Roku', scraper: 'GreenhouseScraper', slug: 'roku' },
  { name: 'Runway', scraper: 'AshbyScraper', slug: 'runway' },
  { name: 'Samsara', scraper: 'GreenhouseScraper', slug: 'samsara' },
  { name: 'Scale AI', scraper: 'GreenhouseScraper', slug: 'scaleai' },
  {
    name: 'Sentry',
    scraper: 'AshbyScraper',
    slug: 'sentry',
    domains: ['sentrycareers.com'],
  },
  { name: 'Serval', scraper: 'AshbyScraper', slug: 'serval' },
  { name: 'SFMOMA', scraper: 'LeverScraper', slug: 'sfmoma' },
  {
    name: 'Shopify',
    scraper: 'ShopifyScraper',
    slug: 'shopify',
    domains: ['careers.shopify.com'],
  },
  { name: 'Sierra', scraper: 'AshbyScraper', slug: 'sierra' },
  {
    name: 'Sift',
    scraper: 'AshbyScraper',
    slug: 'sift',
    domains: ['siftcareers.com'],
  },
  {
    name: 'Skidmore, Owings & Merrill',
    scraper: 'WorkdayScraper',
    slug: 'som.wd5.External',
  },
  {
    name: 'Slack',
    scraper: 'WorkdayScraper',
    slug: 'salesforce.wd12.Slack',
    domains: ['careers.slack.com'],
  },
  {
    name: 'Snowflake',
    scraper: 'AshbyScraper',
    slug: 'snowflake',
    domains: ['careers.snowflake.com'],
  },
  { name: 'SoFi', scraper: 'GreenhouseScraper', slug: 'sofi' },
  { name: 'SpaceX', scraper: 'GreenhouseScraper', slug: 'spacex' },
  { name: 'Span', scraper: 'AshbyScraper', slug: 'span' },
  { name: 'Spotify', scraper: 'LeverScraper', slug: 'spotify' },
  { name: 'Sprig', scraper: 'AshbyScraper', slug: 'sprig' },
  {
    name: 'Squarespace',
    scraper: 'GreenhouseScraper',
    slug: 'squarespace',
    domains: ['careers.squarespace.com'],
  },
  { name: 'Stripe', scraper: 'GreenhouseScraper', slug: 'stripe' },
  { name: 'Supabase', scraper: 'AshbyScraper', slug: 'supabase' },
  { name: 'Sydecar', scraper: 'AshbyScraper', slug: 'sydecar' },
  { name: 'Tailscale', scraper: 'GreenhouseScraper', slug: 'tailscale' },
  { name: 'Temporal', scraper: 'AshbyScraper', slug: 'temporal' },
  {
    name: 'Thumbtack',
    scraper: 'AshbyScraper',
    slug: 'thumbtack',
    domains: ['careers.thumbtack.com'],
  },
  { name: 'Together AI', scraper: 'GreenhouseScraper', slug: 'togetherai' },
  { name: 'turbopuffer', scraper: 'AshbyScraper', slug: 'turbopuffer' },
  { name: 'Twilio', scraper: 'GreenhouseScraper', slug: 'twilio' },
  { name: 'Twitch', scraper: 'GreenhouseScraper', slug: 'twitch' },
  {
    name: 'Uber',
    scraper: 'UberScraper',
    slug: 'uber',
    domains: ['jobs.uber.com'],
  },
  { name: 'Unify', scraper: 'AshbyScraper', slug: 'unify' },
  {
    name: 'UserTesting',
    scraper: 'WorkdayScraper',
    slug: 'usertesting.wd12.UserTesting',
  },
  { name: 'Valon', scraper: 'AshbyScraper', slug: 'valon' },
  { name: 'Vanta', scraper: 'AshbyScraper', slug: 'vanta' },
  { name: 'Vercel', scraper: 'GreenhouseScraper', slug: 'vercel' },
  {
    name: 'Verily',
    scraper: 'WorkdayScraper',
    slug: 'verily.wd1.Verily_Careers',
  },
  { name: 'Waymo', scraper: 'GreenhouseScraper', slug: 'waymo' },
  { name: 'Webflow', scraper: 'GreenhouseScraper', slug: 'webflow' },
  { name: 'Weekend', scraper: 'AshbyScraper', slug: 'weekend' },
  { name: 'Wispr Flow', scraper: 'AshbyScraper', slug: 'wispr-flow' },
  { name: 'Workato', scraper: 'GreenhouseScraper', slug: 'workato' },
  { name: 'xAI', scraper: 'GreenhouseScraper', slug: 'xai' },
  { name: 'XBOW', scraper: 'AshbyScraper', slug: 'xbowcareers' },
  { name: 'Zapier', scraper: 'AshbyScraper', slug: 'zapier' },
  { name: 'Zip', scraper: 'AshbyScraper', slug: 'zip' },
  { name: 'Zscaler', scraper: 'GreenhouseScraper', slug: 'zscaler' },
];
